"""Add title field to memberships

Revision ID: 02970bf2734d
Revises: 78bd9c2ac918
Create Date: 2025-07-01 05:20:31.896313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02970bf2734d'
down_revision = '78bd9c2ac918'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        # First add the column as nullable
        batch_op.add_column(sa.Column('title', sa.String(length=100), nullable=True))
    
    # Update existing records with a default title
    op.execute("UPDATE memberships SET title = 'Membership #' || id WHERE title IS NULL")
    
    # Now make the column non-nullable
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.alter_column('title', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###
