"""Remove created_by from equipment_blocked_dates

Revision ID: 0b36e8ae4f91
Revises: 8497809a0c27
Create Date: 2025-07-23 05:40:53.938653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b36e8ae4f91'
down_revision = '8497809a0c27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment_blocked_dates', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('equipment_blocked_dates_created_by_fkey'), type_='foreignkey')
        batch_op.drop_column('created_by')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment_blocked_dates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('equipment_blocked_dates_created_by_fkey'), 'users', ['created_by'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###
