"""Make blocked dates global instead of per-equipment

Revision ID: 0e2d44a013dd
Revises: 1e57fc831f34
Create Date: 2025-07-23 05:14:58.809457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e2d44a013dd'
down_revision = '1e57fc831f34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment_blocked_dates', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('equipment_blocked_dates_equipment_id_fkey'), type_='foreignkey')
        batch_op.drop_column('equipment_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment_blocked_dates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('equipment_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('equipment_blocked_dates_equipment_id_fkey'), 'equipment', ['equipment_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
