"""Add cost and notes to memberships

Revision ID: 338465c0938e
Revises: e37955bd3528
Create Date: 2025-06-30 04:08:09.043095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '338465c0938e'
down_revision = 'e37955bd3528'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.drop_column('notes')
        batch_op.drop_column('cost')

    # ### end Alembic commands ###
