"""Remove original_input from tasks, use description for full text with tags

Revision ID: 5bfdf79b78ef
Revises: 89371be38419
Create Date: 2025-07-01 13:26:27.964996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bfdf79b78ef'
down_revision = '89371be38419'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('original_input')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_input', sa.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
