"""Add title to memberships

Revision ID: 89371be38419
Revises: 
Create Date: 2025-07-01 13:15:15.669252

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column


# revision identifiers, used by Alembic.
revision = '89371be38419'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # Add title column as nullable first
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=100), nullable=True))
    
    # Create a table representation for the update
    memberships_table = table('memberships',
        column('id', sa.Integer),
        column('title', sa.String)
    )
    
    # Set default titles for existing memberships
    op.execute(
        memberships_table.update().values(
            title=op.inline_literal('Membership #') + memberships_table.c.id
        )
    )
    
    # Now make the column non-nullable
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.alter_column('title',
                            existing_type=sa.String(length=100),
                            nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.drop_column('title')
    # ### end Alembic commands ###
