"""Add membership status and supplements

Revision ID: 90669c297085
Revises: a68a9ec1819f
Create Date: 2025-07-02 07:30:26.149993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90669c297085'
down_revision = 'a68a9ec1819f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), server_default='Active', nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
